import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/layout-components/navbar/navbar';
import Footer from '@/components/layout-components/footer/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
